name: build

on:
  push:
    branches: [ main ]

jobs:

  vet-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.18]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Vet backend
        run: go vet --all .

      - name: Test backend
        run: go test -v -race .
